# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bdb1}
  s.version = "0.2.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Guy Decoux}, %q{Akinori MUSHA}]
  s.date = %q{2012-01-02}
  s.description = %q{This is a Ruby interface to Berkeley DB 1.85 and 1.86.}
  s.email = %q{knu@idaemons.org}
  s.extensions = [%q{ext/bdb1/extconf.rb}]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Changes",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bdb1.gemspec",
    "examples/basic.rb",
    "examples/func.rb",
    "examples/recno.rb",
    "examples/record.rb",
    "examples/wordtest",
    "examples/zeroc.rb",
    "ext/bdb1/bdb1.c",
    "ext/bdb1/bdb1.h",
    "ext/bdb1/delegate.c",
    "ext/bdb1/extconf.rb",
    "ext/bdb1/recnum.c",
    "test/helper.rb",
    "test/test_btree.rb",
    "test/test_hash.rb",
    "test/test_marshal.rb",
    "test/test_recnum.rb",
    "test/tmp/.keep_me"
  ]
  s.homepage = %q{http://github.com/knu/ruby-bdb1}
  s.licenses = [%q{Ruby's}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{A Ruby interface to Berkeley DB 1.85 and 1.86}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rake-compiler>, [">= 0.7.9"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rake-compiler>, [">= 0.7.9"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rake-compiler>, [">= 0.7.9"])
  end
end

